### ISSUE TITLE
Should `Events` trait take `self` by value?

### ISSUE THREAD

**Issue by ns-cweber** [PistonDevelopers/piston#1026]
I'm new to Rust, so pardon my ignorance; however, it seems like the `Events` trait should take `self` by reference (or the `WindowSettings` implementation should be copyable) so that calling `window_settings.events()` doesn't move the WindowSettings object. Because `Rc<RefCell<WindowSettings>>` implements `Events`, we can get around the problem, but it seems like it shouldn't be necessary to use runtime sharing to invoke multiple read methods from different contexts (a la the following code sample). If there's another solution or some reason reference counting is necessary, please inform me.

``` rust
fn main() {
    let opengl = OpenGL::V3_2;

    // Create an Glutin window.
    let window = WindowSettings::new("spinning-square", [200, 200])
                     .opengl(opengl)
                     .exit_on_esc(true)
                     .build()
                     .unwrap();

    let mut app = App {
        gl: GlGraphics::new(opengl),
        x: 0.0,
        y: 0.0,

        // hanging onto the reference so the app can query window size
        // in its `update()` method
        window: &window,
    };

    // `events()` takes `self` by value, but `window` is not copyable,
    // so it must be moved (except it can't be moved because `window`
    // is borrowed by `app`)
    for e in window.events() {
        if let Some(r) = e.render_args() {
            app.render(&r);
        }

        if let Some(u) = e.update_args() {
            app.update(&u);
        }
    }
}
```

**Comment by bvssvni** [comment]
Put the window in an `Rc<RefCell<T>>`:

```Rust
let window = Rc::new(RefCell::new(window));
```

Then put one copy using `.clone()` in the `App` structure. When accessing the window you need to use `.borrow()` or `.borrow_mut()`.

The reason you can't do `&window` is because the event loop need to mutate the window. While the window is not mutated at the same time, the Rust compiler is not that smart and we need `Rc<RefCell<T>>` for dynamic borrow checking.

My common advice to people new to Rust: Learn to use smart pointers where they are appropriate. Think of lifetimes as an optimization more than a design feature. You will be more productive.

**Comment by ns-cweber** [comment]
I see. It seems like Rust isn't living up to it's promise of zero-cost abstraction here. :( Thanks very much for the advice and explanation, nevertheless.

**Comment by bvssvni** [comment]
Closing.

**Comment by mitchmindtree** [comment]
@ns-cweber @bvssvni Just for the record, I don't think it would be a big problem to make the event loop not borrow the window, i.e. instead of making `Events` an iterator, we could do something like this:

```rust
let mut events = window.events();
while let Some(event) = events.next(&mut window) {
    // Here we still have unique access to the window as the event loop
    // only requires mutable access to the window for the duration of
    // the call to `event.next(&mut window)`.
}
```

This would remove the need for any smart pointers providing a nice zero-cost abstraction for the loop. We also use this same method to solve ownership issues during graph traversal in daggy and petgraph - we use this [`Walker`](http://mitchmindtree.github.io/daggy/daggy/walker/trait.Walker.html#tymethod.next) abstraction which only borrows for the lifetime of `next`, rather than `Iterator` whose borrow lasts for the lifetime of the iterator itself.

Also, I would be weary of recommending `Rc<RefCell<T>>` to newcomers for a few reasons:
- although it may feel more productive initially, it can cause limitations further into a project as ownership over `T` can become ambiguous
- it immediately sacrifices one of the properties that makes rust nice in the first place which is the compile-time no-aliasing guarantees
- it can be difficult to refactor if the user ends up deciding they want to thread parts of their program

In my limited experience I've found that, although it can be slightly more work to find a non-`Rc<RefCell<T>>` solution, the pay-off is normally worth it in the long-run.

At the same time, I totally acknowledge that it can be useful at times :) for example, it assists us a lot with sharing the `GlyphCache` in conrod, and it can also be useful for thread_local global storage. Though now that I mention it, I think these are the only use-cases I've personally come across for `RefCell`. I'm not suggesting that others don't exist, just pointing out to @ns-cweber that most of the time, nice zero-cost solutions do exist.

**Comment by bvssvni** [comment]
@mitchmindtree I think this is a good idea!

**Comment by ns-cweber** [comment]
@mitchmindtree Thanks very much for the detailed response. Very informative!
