### ISSUE TITLE
Disable CI for repos that break on stable

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1050]
There is an upcoming breaking change in Rust for `pub extern crate`. See https://github.com/rust-lang/rust/pull/31362. Currently, this is a warning on beta and nightly releases. We can choose to break stuff now or later, so we will break stuff now.

**People are recommended to use beta or nightly until next Rust stable release (1.8).**

CI will be disabled temporarily where this is a problem, and turn back on next Rust stable release.

Here is a list of repos where CI is disabled:

- [x] gfx_graphics
- [x] piston_window
- [x] opengl_graphics
- [x] Piston-Tutorials
- [x] piston-examples

**Comment by mitchmindtree** [comment]
In the future, I would personally choose "break later" if "break now" means not being able to build on stable.

I realise that the next working stable release is only a week away and this really isn't a big deal, but I just wanted to mention that I think we should take our commitment to building consistently on stable very seriously (so far, I've managed to avoid having to use an unstable build of Rust since `1.0.0` landed, and it would be a real pity to without a very strong reason) :smile_cat:

**Comment by bvssvni** [comment]
I was not aware of this breakage until it was too late, so I decided to continue based on too little information. It is quite complicated now since there are many things that need to be tested at once, and because of the demanding recent upgrades I was not in good enough shape to avoid all mistakes. The mistake I did was not account for information I did not know at that moment. Normally this would not happen, but because of many complicated reasons, this error sneaked it.

There is no change in the commitment to building on stable. Next time we'll wait fixing the warnings until it works on stable.

**Comment by Ryman** [comment]
Does anybody have a link to the relevant rust issue for this?

**Comment by bvssvni** [comment]
@Ryman I updated the top comment with link to the Rust PR.

**Comment by mitchmindtree** [comment]
Oh I didn't realise it was a mistake! No problem at all sir, these things happen :smile:

**Comment by bvssvni** [comment]
Rust 1.8 is released. Closing.

**Comment by sunjay** [comment]
You should update the note [here](https://github.com/PistonDevelopers/Piston-Tutorials/tree/master/getting-started) now that it's out.
