### ISSUE TITLE
expose current time in UpdateArgs

### ISSUE THREAD

**Issue by radix** [PistonDevelopers/piston#1134]
Currently UpdateArgs exposes the "dt", the time delta since the last update.

It would be nice to also have access to the current time without having to make a second call to `precise_time_ns` in my game code. I need this for certain things -- for example, rate limiting. I want to store the last (absolute) time that a bullet was fired before firing again. Maybe I'm missing something and there's a better way to do what I'm trying to do.

If this idea is acceptable I am willing to provide a PR to implement this feature.

**Comment by bvssvni** [comment]
If you want your game code to be deterministic, simply sum the update deltas and use it as a timer. You can also start with the trigger repeat time and subtract, to fire a new bullet when it reaches zero.

The current semantics of `UpdateArgs` is well defined. Calling `precise_time_ns` in game code means something else (it is not deterministic). If we pass over the information from the event loop, we loose guarantee that depending on `UpdateArgs` leads to deterministic behavior, and introduce a problem for another design concern: `UpdateArgs` is relative to allow event transformation, like in AI behavior trees https://github.com/PistonDevelopers/ai_behavior/blob/master/src/state.rs#L132.

To give you some background I'll explain a bit about the semantics and philosophy of the Piston core:

- All games have in common that their behavior depends on some infinite set of events produced by the game loop
- The set is infinite because we can not predict in advance the whole set for all platforms, hardware etc. Therefore, Piston's event model use `GenericEvent` instead of just an enum.
- Semantics of events are often better processed when smaller and isolated, e.g. relative mouse movement in FPS is independent of mouse cursor position
- Events should be transformable (relative), to reuse code across an additional dimension of semantics, e.g. widget hierarchies

**Comment by radix** [comment]
Oh, yes, I was shortsighted in my suggestion. It's been a while since I've done this type of event-loop work, so I am rusty :)

I guess what I would really like is a scheduling system (I'm thinking: modular clocks that can be paused and resumed independently, and have some function for scheduling events for N us in the future). I'll probably implement something like that in my game code and then see how well it can be abstracted out for potential contribution to Piston.

Thanks for the info :)

**Comment by bvssvni** [comment]
I would not say "shortsighted", since you can not anticipate what are unknown unknowns. Reality are just more complex than what human brains can model upfront. The design of Piston is a result of hindsight, where improvements come from running into walls. You are probably as good as anyone involved in the design, no magic thinking here.

New projects are always welcome 👍
