### ISSUE TITLE
[question] How to draw pixels

### ISSUE THREAD

**Issue by trsh** [PistonDevelopers/piston#1175]
Mostly graphic engines, besides rectangles, lines etc., have a function to put a single pixel on the screen. It's very handy for complex visualizations. How it could be done in Piston?

**Comment by bvssvni** [comment]
See https://github.com/PistonDevelopers/piston-examples/blob/master/src/image.rs

You can set individual pixels in an image, then update a texture and render it to the screen.

**Comment by trsh** [comment]
@bvssvni 

Sorry I did not understand how to "_set individual pixels in an image_". I think the example only covers, how to render a texture and I did not found any info in docs (http://docs.piston.rs/graphics/graphics/image/struct.Image.html). I need to put pixels at run-time, with some code logic.

**Comment by trsh** [comment]
@bvssvni 

I really suggest to make a function like 

rectangle([1.0, 0.0, 0.0, 1.0], [0.0, 0.0, 100.0, 100.0], c.transform, g);

but for pixels pixel([1.0, 0.0, 0.0, 1.0], x, y, ...)

because sometimes primitives like lines and rectangles are not enough or to much. :)

**Comment by bvssvni** [comment]
It is much slower to render a rectangle for every pixel than changing the image, because first it gets triangulated into two parts, then written to a chunk and sent to the graphics backend that puts the chunk in a buffer and flushes it later. Then the GPU receives the buffer.

When you work with an image using CPU, update and render it as a texture, it takes only 2 triangles.

**Comment by bvssvni** [comment]
Oh. I used the wrong link. Here https://github.com/PistonDevelopers/piston-examples/blob/master/src/paint.rs

**Comment by trsh** [comment]
@bvssvni tnx
