### ISSUE TITLE
[question] future of piston game engine

### ISSUE THREAD

**Issue by trsh** [PistonDevelopers/piston#1176]
As from commit's I see there hasn't been any serious updates for the game engine it self and The main developer seems to be busy with more important stuff (ex. path semantics).. or something like that.

So what's the plan / the road map for Piston? Will it remain more like a low level game framework or are there some plans... ? Something? :)

**Comment by bvssvni** [comment]
I am a bit curious of what plans you have in mind, if you have any?

The road map for Piston has always focused on experimentation. Experiment, experiment, experiment. When I figure out something useful, I make it a library. So, I believe this will be future path ahead as well.

Counter-intuitively, waiting and doing nothing while doing something else can sometimes save you time. I worked on a few libraries for Piston though. Played around with VR a bit. Dyon also got some upgrades.

The reason I have been working on path semantics the past few months is because I've finally made a lot of breakthroughs. Normally these occur much more rarely. Recently I've done some work on extending it to probability theory, so now the goals for this project are within sight. Finding algorithms for cross argument paths is a very hard problem...

The reason I have not worked on Piston very much is because the research have taken up too much time, and I have to get through some climate science papers and geoengineering stuff since it is the most important issue of our time, and a very complex one too. I can't afford being ignorant, but now I get the big picture and is mostly interested in how to expand the toolbox for path semantics into applications for physics.

For the future, I plan to use Piston for some projects, and as Gfx improves I think graphics_tree and other libraries will become more useful. The biggest pain point now is text rendering, but I've improved the performance a bit for opengl_graphics. This is such a complicated issue that I need more time to investigate, but there are already people working on different ideas such as in Servo where they do glyphs on the GPU. Waiting means I can save myself some work.

**Comment by trsh** [comment]
> I am a bit curious of what plans you have in mind, if you have any?

1) I want to simulate some Wave algorithms for personal project (I'm kind of scientist with no degree :D), that I'm working now. For that I was asking about that Pixel thing in previous issue.

2) At my workplace we plan to develop some apps. Requirements are good compatibility with VR's and modern shading stuff (PBS, soft shadows, blur, etc).

**Comment by bvssvni** [comment]
Cool! I also think it annoying to not have a set pixel method, but using an image should be faster. You could also use Rayon to speed it up!

The current strategy of Piston is to use a minimal core design because the Rust community as a whole will always be better than any team (obviously since the team is part of the Rust community). I plan to make it easier to get started with VR, got some code working for OpenGL, but not ready yet. I would like to work on rendering too, but looking at my time schedule it's "nope, that's way too much". There are other people working on it, so I hope to see some useful libraries popping up over time.

I have a degree in computer science and artificial intelligence, then did consulting and worked on 2D animation software for a decade until I fell in love with mathematics (I always liked it but did not understand the deeper ideas). I want to make some of those invisible deep stuff more visible and accessible. I learned to see programming in a different way that isn't just about making apps, but more about feedback between human thinking and formal languages and representations (this was also how modern computers where invented). This is why I like to work on Piston, because you can get rid of some of the technical barriers and concentrate on the idea in your head. I probably think too much about big picture problems too, but it is very hard for me to pretend everything is OK and not discuss or think about it, and who knows, perhaps we learn something new?

I want the Piston project to be a place where people can share ideas and code, help out with maintenance, experiment and do research, which is not the same as just building a game engine. There are already very good game engines out there. I feel the need for a place where people are encouraged to experiment and where you can influence the direction of a project. I am all for separation of concerns when it is about code, but for people to be creative you need a melting pot of ideas and some very hard challenges. I like working like this. :)

**Comment by trsh** [comment]
@bvssvni would be very cool, if you hit me in some direction how can I achieve run-time pixels with Image. because I didn't get it from your example.

**Comment by bvssvni** [comment]
@trsh I sent you the wrong link. Added a comment on the issue https://github.com/PistonDevelopers/piston/issues/1175#issuecomment-300761657

**Comment by trsh** [comment]
tnx

**Comment by trsh** [comment]
@bvssvni 

`I probably think too much about big picture problems too, but it is very hard for me to pretend everything is OK and not discuss or think about it...`

Yeah. Pumping new effects for games while our planet and lifes go to hell, is not the smartest plan :D. I am totally in with you on this. And I make sure that my work/ideas outside survival jobs (for paying rent, etc) do count for bigger picture.
