### ISSUE TITLE
Hidden surface removal

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#832]
http://www.cs.sun.ac.za/~lvzijl/courses/rw778/grafika/OpenGLtuts/Big/graphicsnotes009.html

* Descriptions of different techniques, including z-buffer and BSP trees

**Comment by indiv0** [comment]
Just as a thought: I know that currently this is the accepted way to document relevant information, but perhaps we should attempt to migrate information like this to the wiki to centralize it a bit and separate it from actual issues?

I know that currently we use the information tag for this purpose, but I think that this deserves some consideration into separation of concerns.

The biggest pros (IMO) would be the ability to track changes effectively, isolate info from actual issues, and be able to point users to a centralized source of information instead of "check the issues".

**Comment by bvssvni** [comment]
The biggest problem with the wiki is that it's not searchable.

**Comment by bvssvni** [comment]
@indiv0 I opened https://github.com/PistonDevelopers/piston/issues/834
