### ISSUE TITLE
Start an "official" window back-end using Gfx and Glutin

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#880]
Gfx got some abstractions now that require integration between window and graphics. We could add a library `gfx_window` to glue this to wrapped piston window abstractions, or we could start a `piston_window` that uses Glutin directly.

The argument is as following: If you want to use Gfx, which you need to use many 3D Piston libraries, then why would you want to use SDL2 or GLFW when Piston does the event abstraction, and Glutin provides a cross platform interface?

**Comment by Potpourri** [comment]
`piston_window` will work only with `gfx`? I.e. it will be `glutin_window` + impl `gfx::Output` + impl `gfx::Window`?

**Comment by mitchmindtree** [comment]
+million! :+1:

I think this will also provide the opportunity to vastly simplify the setup of the window for users of piston as well who just want to get something going.

I agree that glutin and gfx sound like a great combo for this - it removes the need for any C bindings as would be the case with sdl2 and glfw as well.

**Comment by bvssvni** [comment]
@Potpourri Yes, but I'm thinking of possibilities for the future as well.

The piston core allows custom events, but the piston back-end could support events that integrates with other Piston libraries.

**Comment by Potpourri** [comment]
If we also create the same for glium, then I agree.

**Comment by bvssvni** [comment]
Name suggestions for the Glium library?

**Comment by Potpourri** [comment]
Name... I don't know.
`sdl2_window` and `glfw_window` still be supported? But `gfx_graphics` might be used only with `piston_window`?

**Comment by mitchmindtree** [comment]
@Potpourri I don't think this means that any of the other repos or backends will no longer be supported, it just means we'll be able to have a single "official" `piston-window` repo in which we can abstract away more of the cruft caused by using purely generic APIs - users will still be able to use generic, custom window configurations with different backends, etc by using the repos that already exist.

In having a single `piston-window` repo in which we don't have to worry about being generic over the window and graphics backends, we can make a super tight, neat API for users who don't care about what the backends are and who just want to get a window and some graphics running.

`glutin` is the nicest (only?) cross-platform purely rust window backend and `gfx` is tightly tied into a lot of piston stuff already - they seem like great choices for going ahead in piston's case. If a user wanted to make their own `glutin` + `glium` window (or whatever combo) then I imgaine they'd still be able to do so using piston's abstractions.

**Comment by Potpourri** [comment]
@mitchmindtree Then, we need and `gfx_window`, `glium_window` (as wrapper for flexibility) and `piston_window` (as high-level interface).

**Comment by mitchmindtree** [comment]
Hmmm, why would we need `glium_window` if you can already use `glutin_window` + `glium` together? I can understand the desire for a `gfx_window` due to the issue bvssvni mentioned in the first comment, but what is the extra abstraction/flexibility that `glium_window` would provide?

**Comment by bvssvni** [comment]
To be clear: I want to make Gfx the officially supported 3D api for Piston as a "game engine". While the core supports Glium and other back-ends, they can be thought of as ways to plug into the ecosystem, but you can not expect to get all the features of the whole engine.

**Comment by mitchmindtree** [comment]
:+1:

**Comment by Potpourri** [comment]
@mitchmindtree `glium` require implement own `Facade`,  `Backend` traits, currently it implemented only in `glium_graphics`. We can't use `glutin_window` + `glium`. If `piston_window` will be single implementation gfx window traits, then `gfx_graphics` we might use only with `piston_window` and only with `glutin`.
@bvssvni OK.

**Comment by bvssvni** [comment]
What about `glium_window` for Glium/Glutin?

**Comment by Potpourri** [comment]
@bvssvni yeah, it right name.

**Comment by mitchmindtree** [comment]
@Potpourri ahh my apologies, I thought I'd seen `glium` working with `glutin` before, but I must have been thinking of `glium_graphics` (so many abstractions to track), my mistake :)

**Comment by bvssvni** [comment]
Btw, I'll take rest of the day off, being sick for some days.

**Comment by Potpourri** [comment]
@bvssvni Get well soon!

**Comment by bvssvni** [comment]
I've created https://github.com/pistondevelopers/piston_window
