### ISSUE TITLE
Unify `motion` enum to single-dimension

### ISSUE THREAD

**Issue by Gyscos** [PistonDevelopers/piston#995]
Buttons (keys or mouse buttons) are nicely unified, and the actual action (`Press` or `Release`) is stored separately - in an orthogonal structure.

The `input::Motion` enum on the other hand is a weird one: some components (`MouseCursor`) are two-dimensional, some (`JoystickAxis`) are one-dimensional, and some (`MouseRelative`, `MouseScroll`) could be two-dimensional, but happen to always be one-dimensional on my setup (linux, SDL2 window). It makes unifying its handling tricky.

Instead, maybe always using one dimension, and separating the source (`MouseCursor`, `JoystickAxis::{id,axis}`) from the actual value (`JoystickAxis::position`) could be considered?

We'd have then:
```rust

enum Direction {
    X,
    Y,
}

struct JoystickAxisArgs {
    id: i32,
    axis: u8,
}

enum MotionSource {
    MouseCursor(Direction),
    MouseRelative(Direction),
    MouseScroll(Direction),
    JoystickAxis(JoystickAxisArgs),
}

struct Motion {
    source: MotionSource,
    value: f64,
}
```

It would also allow to derive Hash for MotionSource.

Possible problems would be:
* Further from low-level inputs (this unification is a high-level concept, not a low-level one)
* Trickier to get the mouse `(x,y)` position, the same way it's tricky right now to get two joystick axis at the same time.

**Comment by bvssvni** [comment]
Usually you use the event traits instead of matching against the enum.

I kind of like the idea that it becomes more symmetric, but believe there are more downsides:

- It will break a lot of code in a very inconvenient way (getting the mouse cursor position will be painful).
- We need an extra state in the window back-end to track y value of mouse coordinates (we try to avoid state in window back-ends as much as possible, because that's usually always a bad thing).

From a pragmatic point of view, I don't think we should make this change.

Joysticks have separate events because they can have 1D, 2D, 3D or more axes. We are doing it this way because that is how SDL2 does it. At some point in the future we will develop a cross platform library for input controllers in pure Rust to make this better. See https://github.com/PistonDevelopers/piston/issues/884.
